### ISSUE TITLE
Importing Raw files from TC2 example stamps are clipped.

### ISSUE THREAD

**Issue by geekrelief** [Seneral/TC2-Node-Painter-Beta#12] opened 2017-03-04 02:41 UTC
Are TC2 Raw Images and Node Painter Raw images compatible?  This shows the BumpyIsland stamp loaded via Import Raw and the values are clipped.

![raw_clipped](https://cloud.githubusercontent.com/assets/27040/23575437/0ae1fb0c-0041-11e7-8188-73fe63c0491b.png)

**Comment by Seneral** [comment] 2017-03-04 17:51
Can reproduce that. Format-wise, there should be no problem - they are 4096x4096 and 16Bit. So there is probably an error in my code... I load them in manually instead of using the built-in function TC2 uses because that would require the format of the Texture to be grayscale, but internally I always work on full RGBA textures (currently) so I have to load them in manually...

**Comment by Seneral** [comment] 2017-03-04 22:10
Fixed in beta 1.3

**Closed by Seneral** 2017-03-04 22:10 UTC
